name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  formatting-check:
  
    name: Formatting Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v4.5.0
      with:
        clang-format-version: '12'

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag oclhelpers
      
    - name: Start the container
      run: |
        docker run --name oclhelpers --network host -v $(pwd):/oclhelpers oclhelpers:latest
        docker start oclhelpers
      
    - name: Configure the project
      run: |
        docker exec -d oclhelpers mkdir build
        docker exec -d oclhelpers cmake -B/build -S/oclhelpers -DENABLE_TESTS=on
        
    - name: Build the project
      run: docker exec -d oclhelpers cmake --build /build --parallel 4
      
    - name: Test
      run: docker exec -d oclhelpers bash /build/test/test
